import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen  bg-purple-500">
        <Navbar />
      </main>
    </>
  );
};

export default Home;
