import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "./components/Navbar";
import Post from "./components/Post";
import Posts from "./components/Posts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen  bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 pb-10">
        <Navbar />
        <Post />
        {/* // User Posts // */}
        <Posts />
      </main>
    </>
  );
};

export default Home;
