import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Chat T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-purple-500">
        <div className="flex flex-col items-center">
          <h1 className="text-[100px] font-bold text-white">Chat T3</h1>
          <button className="w-1/2 rounded-md bg-purple-800 p-2 font-semibold text-white hover:bg-purple-900">
            Login with Discord
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
